# ----------------------------------------------------------------------------
#
# Package             : helm
# Source Repo         : https://github.com/alpine-docker/helm
# Travis Job Link     : https://travis-ci.com/github/asellappen/helm/
# Created travis.yml  : No
# Maintainer          : Arumugam N S <asellappen@yahoo.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
sudo: required

services:
  - docker
env:
  global:
    -  DOCKER_USERNAME=[secure]
    -  DOCKER_PASSWORD=[secure]
jobs:
  include:
    - stage: build amd64
      script: 
      - bash -x ./build.sh
    - stage: build ppc64le
      arch: ppc64le
      before_script:
      - sudo apt-get -qq update
      - sudo apt-get -y install jq
      script:
      - bash -x ./build.sh
