# ----------------------------------------------------------------------------
#
# Package             : helm
# Source Repo         : https://github.com/alpine-docker/helm
# Travis Job Link     : https://travis-ci.com/github/asellappen/helm/
# Created travis.yml  : No
# Maintainer          : Arumugam N S <asellappen@yahoo.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
language: generic
sudo: required
arch:
  - amd64
  - ppc64le

services:
  - docker
  
before_install:
  - sudo apt-get install jq
script:
  - docker login -u "gitlab-ci-token" -p $CI_JOB_TOKEN $CI_REGISTRY
  - sudo bash ./build.sh
